### ISSUE TITLE
大佬，拉下代码来打包报错

### ISSUE THREAD

**Issue by YLQZ** [umbrella22/electron-vite-template#50]
1.拉取代码，
2.设置环境及安装环境（根据doc网站上那样设置，安装工具用yarn）
3. 安装好后 yarn dev 桌面软件可启动
4.  打包 yarn build  / yarn build:win64  等 均报错 大概意思是 main进程的文件没有打包出来 所以报错
跪求解决指导一下
 错误信息：

 OKAY  take it away `electron-builder`

  • electron-builder  version=23.0.3 os=10.0.22000
  • loaded configuration  file=E:\Study\vue\electron-vite-template\build.json
  • writing effective config  file=build\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=17.2.0 appOutDir=build\win-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  ⨯ Application entry file "E:\Study\vue\electron-vite-template\build\win-unpacked\resources\app\dist\electron\main\main.js" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "E:\Study\vue\electron-vite-template\build\win-unpacked\resources\app\dist\electron\main\main.js" does not exist. Seems like a wrong configuration.
    at WinPackager.checkFileInPackage (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\platformPackager.ts:528:15)
    at WinPackager.sanityCheckPackage (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\platformPackager.ts:551:5)
    at WinPackager.doPack (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\platformPackager.ts:312:5)
    at WinPackager.pack (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (E:\Study\vue\electron-vite-template\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (E:\Study\vue\electron-vite-template\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (E:\Study\vue\electron-vite-template\node_modules\builder-util\src\promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by umbrella22** [comment]
嗯，确认bug，今日内修复

**Comment by umbrella22** [comment]
已修正，请重新拉取后再试

**Comment by YLQZ** [comment]
OK，已确认修复，gitee同步吧
